CREATE FUNCTION dbo.TestFunctionIF() RETURNS TABLE AS RETURN SELECT 13 Column1;
GO
CREATE FUNCTION dbo.FakeFunctionIF() RETURNS TABLE AS RETURN SELECT 42 Column1;
GO

CREATE FUNCTION dbo.TestFunctionIF_P1(@P1 int) RETURNS TABLE AS RETURN SELECT 13+@P1 Column1;
GO
CREATE FUNCTION dbo.FakeFunctionIF_P1(@P1 int) RETURNS TABLE AS RETURN SELECT 42+@P1 Column1;
GO

CREATE FUNCTION dbo.TestFunctionTF() RETURNS @Result TABLE (Column1 int) AS BEGIN INSERT INTO @Result SELECT 13; RETURN; END;
GO
CREATE FUNCTION dbo.FakeFunctionTF() RETURNS @Result TABLE (Column1 int) AS BEGIN INSERT INTO @Result SELECT 42; RETURN; END;
GO

CREATE FUNCTION dbo.TestFunctionTF_P1(@P1 int) RETURNS @Result TABLE (Column1 int) AS BEGIN INSERT INTO @Result SELECT 13+@P1; RETURN; END;
GO
CREATE FUNCTION dbo.FakeFunctionTF_P1(@P1 int) RETURNS @Result TABLE (Column1 int) AS BEGIN INSERT INTO @Result SELECT 42+@P1; RETURN; END;
GO

CREATE FUNCTION dbo.TestFunctionScalar() RETURNS INT AS BEGIN RETURN (SELECT 13); END;
GO
CREATE FUNCTION dbo.FakeFunctionScalar() RETURNS INT AS BEGIN RETURN (SELECT 42); END;
GO

CREATE FUNCTION dbo.TestFunctionScalar_P1(@P1 int) RETURNS INT AS BEGIN RETURN (SELECT 13+@P1); END;
GO
CREATE FUNCTION dbo.FakeFunctionScalar_P1(@P1 int) RETURNS INT AS BEGIN RETURN (SELECT 42+@P1); END;
GO

CREATE TABLE dbo.FakeDataSource (Column1 int);
GO

CREATE TYPE dbo.TestType AS TABLE (Column1 int);
GO

CREATE FUNCTION dbo.TestFunctionIF_P1_TT(@P1 int, @P2 dbo.TestType READONLY) RETURNS TABLE AS RETURN SELECT (SELECT 13+SUM(Column1)+@P1 FROM @P2) Column1;
GO
CREATE FUNCTION dbo.FakeFunctionIF_P1_TT(@P1 int, @P2 dbo.TestType READONLY) RETURNS TABLE AS RETURN SELECT (SELECT 42+SUM(Column1)+@P1 FROM @P2) Column1;
GO

CREATE FUNCTION dbo.TestFunctionTF_P1_TT(@P1 int, @P2 dbo.TestType READONLY) RETURNS @Result TABLE (Column1 int) AS BEGIN INSERT INTO @Result SELECT 13+SUM(Column1)+@P1 FROM @P2; RETURN; END;
GO
CREATE FUNCTION dbo.FakeFunctionTF_P1_TT(@P1 int, @P2 dbo.TestType READONLY) RETURNS @Result TABLE (Column1 int) AS BEGIN INSERT INTO @Result SELECT 42+SUM(Column1)+@P1 FROM @P2; RETURN; END;
GO

CREATE FUNCTION dbo.TestFunctionScalar_P1_TT(@P1 int, @P2 dbo.TestType READONLY) RETURNS INT AS BEGIN RETURN (SELECT 13+SUM(Column1)+@P1 FROM @P2); END;
GO
CREATE FUNCTION dbo.FakeFunctionScalar_P1_TT(@P1 int, @P2 dbo.TestType READONLY) RETURNS INT AS BEGIN RETURN (SELECT 42+SUM(Column1)+@P1 FROM @P2); END;
GO