CREATE FUNCTION dbo.TestFunctionIF()
RETURNS TABLE AS
RETURN
SELECT 1 Column1;
GO

CREATE FUNCTION dbo.TestFunctionIF_P1(@P1 int)
RETURNS TABLE AS
RETURN
SELECT 1+@P1 Column1;
GO

CREATE FUNCTION dbo.TestFunctionTF()
RETURNS @Result TABLE (Column1 int)
AS BEGIN
INSERt INTO @Result
SELECT 1;
RETURN;
END;
GO

CREATE FUNCTION dbo.TestFunctionTF_P1(@P1 int)
RETURNS @Result TABLE (Column1 int)
AS BEGIN
INSERt INTO @Result
SELECT 1+@P1;
RETURN;
END;
GO

CREATE FUNCTION dbo.TestFunctionScalar()
RETURNS INT
AS BEGIN
RETURN
(SELECT 1);
END;
GO

CREATE FUNCTION dbo.TestFunctionScalar_P1(@P1 int)
RETURNS INT
AS BEGIN
RETURN
(SELECT 1+@P1);
END;
GO