CREATE TABLE tSQLt.TestResult
(
    Id INT IDENTITY(1,1) CONSTRAINT [PK__tSQLt_TestResult] PRIMARY KEY CLUSTERED,
    Class NVARCHAR(MAX) NOT NULL,
    TestCase NVARCHAR(MAX) NOT NULL,
    Name AS (QUOTENAME(Class) + '.' + QUOTENAME(TestCase)),
    TranName NVARCHAR(MAX) NULL,
    Result NVARCHAR(MAX) NULL,
    Msg NVARCHAR(MAX) NULL,
    TestStartTime DATETIME2 NOT NULL,
    TestEndTime DATETIME2 NULL
);