name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  test-edge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: mcr.microsoft.com/azure-sql-edge
          - image: mcr.microsoft.com/mssql/server:2019-latest
          - image: mcr.microsoft.com/mssql/server:2022-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            docker pull ${{matrix.image}}
            sqltest runall --image ${{matrix.image}} --project ./latest/tSQLt.Edge.Tests               --cc-include-tsqlt
            sqltest runall --image ${{matrix.image}} --project ./latest/tSQLt.Edge.Tests               --cc-include-tsqlt --collation SQL_Latin1_General_CP1_CS_AS
            sqltest runall --image ${{matrix.image}} --project ./latest/tSQLt.Edge.Tests.CaseSensitive --cc-include-tsqlt
            sqltest runall --image ${{matrix.image}} --project ./latest/tSQLt.Edge.Tests.CaseSensitive --cc-include-tsqlt --collation SQL_Latin1_General_CP1_CS_AS
            sqltest runall --image ${{matrix.image}} --project ./latest/tSQLt.Original.Tests           --cc-disable
            sqltest runall --image ${{matrix.image}} --project ./current/Example.Tests
  test-xmlresult:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: dotnet test ./latest/tSQLt.XmlResult.Tests