name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pwsh SqlServer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name SqlServer
      - name: Unit tests
        shell: pwsh
        run: |
          cd latest
          ./test.ps1
          cd..
          cd current
          ./test.ps1
  build-on-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup sqltest tool
        shell: pwsh
        run: |
          dotnet tool install -g dotnet-sqltest
          docker pull mcr.microsoft.com/azure-sql-edge
      - name: Unit tests
        shell: pwsh
        run: |
          sqltest runall --image mcr.microsoft.com/azure-sql-edge --project ./latest/tSQLt.Edge.Tests
          sqltest runall --image mcr.microsoft.com/azure-sql-edge --project ./latest/tSQLt.Original.Tests
          sqltest runall --image mcr.microsoft.com/azure-sql-edge --project ./current/Example.Tests