name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SA_PASSWORD: StrongP@ssw0rd!
      DB_NAME: tSQLt-edge
    timeout-minutes: 15
    services:
      sqlserver:
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - 1433/tcp
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "${{ env.SA_PASSWORD }}"
          MSSQL_COLLATION: Polish_CI_AS
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0'
      - name: Build tests
        run: dotnet build Tests
      - name: Publish tests
        run: dotnet publish Tests /p:TargetDatabaseName=${{ env.DB_NAME }} /p:TargetUser=sa /p:TargetPassword=${{ env.SA_PASSWORD }} /p:TargetPort=${{ job.services.sqlserver.ports[1433] }}
      - name: Run unit tests
        run: sqlcmd -S localhost,${{ job.services.sqlserver.ports[1433] }} -d ${{ env.DB_NAME }} -U sa -P ${{ env.SA_PASSWORD }} -t 30 -Q "EXEC testSchema.test1"
