name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  test-edge:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            image: mcr.microsoft.com/azure-sql-edge
          - os: ubuntu-latest
            image: mcr.microsoft.com/mssql/server:2019-latest
          - os: ubuntu-latest
            image: mcr.microsoft.com/mssql/server:2022-latest
          - os: windows-latest
            image: cagrin/mssql-server-ltsc2022:2019-latest
            windows: --windows-container
          - os: windows-latest
            image: cagrin/mssql-server-ltsc2022:2022-latest
            windows: --windows-container
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init
      - name: Setup sqltest tool
        shell: pwsh
        run: |
          dotnet tool install -g dotnet-sqltest
          docker pull ${{matrix.image}}
      - name: Unit tests
        shell: pwsh
        run: |
          sqltest runall --image ${{matrix.image}} ${{matrix.windows}} --project ./latest/tSQLt.Edge.Tests --cc-include-tsqlt
          sqltest runall --image ${{matrix.image}} ${{matrix.windows}} --project ./latest/tSQLt.Original.Tests --cc-disable
          sqltest runall --image ${{matrix.image}} ${{matrix.windows}} --project ./current/Example.Tests
  test-xmlresult:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init
      - name: XmlResult tests
        run: dotnet test --configuration Release ./latest/tSQLt.XmlResult.Tests --logger "console;verbosity=normal"