name: Unit tests

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: '6.0'
      - name: Setup pwsh SqlServer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name SqlServer
      - name: Unit tests
        shell: pwsh
        run: |
          cd latest
          ./test.ps1